//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScooterSharing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScooterSharing.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A confirmation code will be sent to your email.
        /// </summary>
        public static string A_confirmation_code_will_be_sent_to_your_email {
            get {
                return ResourceManager.GetString("A_confirmation_code_will_be_sent_to_your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields must be filled.
        /// </summary>
        public static string All_fields_must_be_filled {
            get {
                return ResourceManager.GetString("All_fields_must_be_filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card num.
        /// </summary>
        public static string Card_num {
            get {
                return ResourceManager.GetString("Card_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose tariff.
        /// </summary>
        public static string Choose_tariff {
            get {
                return ResourceManager.GetString("Choose_tariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm code.
        /// </summary>
        public static string Confirm_code {
            get {
                return ResourceManager.GetString("Confirm_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Confirm_password {
            get {
                return ResourceManager.GetString("Confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit: are you sure?.
        /// </summary>
        public static string Exit_are_you_sure {
            get {
                return ResourceManager.GetString("Exit_are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card expiration date.
        /// </summary>
        public static string Expiration_date {
            get {
                return ResourceManager.GetString("Expiration_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish rental.
        /// </summary>
        public static string Finish_rental {
            get {
                return ResourceManager.GetString("Finish_rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it.
        /// </summary>
        public static string Got_it {
            get {
                return ResourceManager.GetString("Got_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is some account details.
        /// </summary>
        public static string Here_is_some_account_details {
            get {
                return ResourceManager.GetString("Here_is_some_account_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        public static string Invalid_email {
            get {
                return ResourceManager.GetString("Invalid email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Last_Name {
            get {
                return ResourceManager.GetString("Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get device location\nRouting unavailable.
        /// </summary>
        public static string Location_unavailable {
            get {
                return ResourceManager.GetString("Location_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched passwords.
        /// </summary>
        public static string Mismatched_passwords {
            get {
                return ResourceManager.GetString("Mismatched_passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough money for deposit.
        /// </summary>
        public static string Not_enough_money_for_deposit {
            get {
                return ResourceManager.GetString("Not_enough_money_for_deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string Offers {
            get {
                return ResourceManager.GetString("Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 8 characters.
        /// </summary>
        public static string Password_must_contain_at_least_8_characters {
            get {
                return ResourceManager.GetString("Password_must_contain_at_least_8_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment amount.
        /// </summary>
        public static string Payment_amount {
            get {
                return ResourceManager.GetString("Payment_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per minute.
        /// </summary>
        public static string per_minute {
            get {
                return ResourceManager.GetString("per_minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Phone_number {
            get {
                return ResourceManager.GetString("Phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        public static string Please_wait {
            get {
                return ResourceManager.GetString("Please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refill.
        /// </summary>
        public static string Refill {
            get {
                return ResourceManager.GetString("Refill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental.
        /// </summary>
        public static string Rental {
            get {
                return ResourceManager.GetString("Rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental cost.
        /// </summary>
        public static string Rental_cost {
            get {
                return ResourceManager.GetString("Rental_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        public static string Reserve {
            get {
                return ResourceManager.GetString("Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR to rent scooter.
        /// </summary>
        public static string Scan_QR_to_rent_scooter {
            get {
                return ResourceManager.GetString("Scan_QR_to_rent_scooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string Select_language {
            get {
                return ResourceManager.GetString("Select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to some important info.
        /// </summary>
        public static string some_important_info {
            get {
                return ResourceManager.GetString("some_important_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something goes wrong.
        /// </summary>
        public static string Something_goes_wrong {
            get {
                return ResourceManager.GetString("Something_goes wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong with server.
        /// </summary>
        public static string Something_wrong_with_server {
            get {
                return ResourceManager.GetString("Something_wrong_with_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start rental.
        /// </summary>
        public static string Start_rental {
            get {
                return ResourceManager.GetString("Start_rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff.
        /// </summary>
        public static string Tariff {
            get {
                return ResourceManager.GetString("Tariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There will be information about tariffs and discounts.
        /// </summary>
        public static string There_will_be_information_about_tariffs_and_discounts {
            get {
                return ResourceManager.GetString("There_will_be_information_about_tariffs_and_discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This scooter already rented.
        /// </summary>
        public static string This_scooter_already_rented_or_reserved
        {
            get {
                return ResourceManager.GetString("This_scooter_already_rented_or_reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To rental details.
        /// </summary>
        public static string To_renting_details {
            get {
                return ResourceManager.GetString("To_renting_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too short card number.
        /// </summary>
        public static string Too_short_card_number {
            get {
                return ResourceManager.GetString("Too_short_card_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too short code.
        /// </summary>
        public static string Too_short_code {
            get {
                return ResourceManager.GetString("Too_short_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too short phone number.
        /// </summary>
        public static string Too_short_phone_number {
            get {
                return ResourceManager.GetString("Too_short_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top up account.
        /// </summary>
        public static string Top_up_account {
            get {
                return ResourceManager.GetString("Top_up_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        public static string User_already_exists {
            get {
                return ResourceManager.GetString("User already exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t exist.
        /// </summary>
        public static string User_doesn_t_exist {
            get {
                return ResourceManager.GetString("User_doesn\'t_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code.
        /// </summary>
        public static string Verification_code {
            get {
                return ResourceManager.GetString("Verification_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw funds.
        /// </summary>
        public static string Withdraw_funds {
            get {
                return ResourceManager.GetString("Withdraw_funds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal of funds.
        /// </summary>
        public static string Withdrawal_of_funds {
            get {
                return ResourceManager.GetString("Withdrawal_of_funds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Qr.
        /// </summary>
        public static string Wrong_Qr {
            get {
                return ResourceManager.GetString("Wrong_Qr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong verification code.
        /// </summary>
        public static string Wrong_verification_code {
            get {
                return ResourceManager.GetString("Wrong verification code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t log out during renting.
        /// </summary>
        public static string You_can_t_log_out_during_renting {
            get {
                return ResourceManager.GetString("You_can\'t_log_out_during_renting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter verification code.
        /// </summary>
        public static string You_must_enter_verification_code {
            get {
                return ResourceManager.GetString("You_must_enter_verification_code", resourceCulture);
            }
        }
    }
}
